### PR TITLE
Allow to set startDate for decade view

### PR DESCRIPTION
**Pull request by mathieu-morchipont**

### CODE REVIEW

**Comment by indrimuska** [comment]
First of all, thank you @mathieu-morchipont for proposing this!

I've just seen the changes you made for this feature. Unfortunately it works only for the *Decade View*, so it requires a little update to make it works for all view, but don't worry, I'll make these changes for you.

Anyway, it seems that you want to set the decade to be shown **every time the picker is opened**, not just at initialization time. This means that if you have `startDate` set to 1998 (decade from 1990 to 1999) and you select a date in the decade 2000-2009, next time you'll open the picker you'll see again the decade 1990-1999, instead of 2000-2009.

My question is if this behavior is expected by users, or they just want to see last selected date when they reopen the picker.

What are your thoughts?

**Comment by mathieu-morchipont** [comment]
In fact if startDate set to 1998 (decade from 1990 to 1999) and I select a date in the decade 2000-2009, next time I'll open the picker I'll see 2000-2009.

Actually I see 1990-1999

**Comment by indrimuska** [comment]
So, do you agree with me that users should see last selected date period instead of the one given by `startDate`?

**Comment by mathieu-morchipont** [comment]
Yes I agree

**Comment by indrimuska** [comment]
Good, I'll make the change in a minute.
Thanks ;)

**Comment by mathieu-morchipont** [comment]
;)

**Comment by indrimuska** [comment]
This feature is now available in [v0.8.3](https://github.com/indrimuska/angular-moment-picker/releases/tag/0.8.3).

**Pull request closed without merging**
