### PR TITLE
Added code to allow resetting date

### PR DESCRIPTION
**Pull request by cmanunes**

### CODE REVIEW

**Comment by cmanunes** [comment]
If there is the need I can add a config option for this

**Comment by indrimuska** [comment]
Hi @cmanunes , this is very interesting feature.

Anyway, instead of updating the current template, I am considering to give users the ability to set their own template inside the picker, so that any button or operation can be added depending on the application. In that case, you'll be able to have something like that:

```html
<!-- your custom contents -->
<div class="btn btn-default" style="width:100%" ng-click="resetDatePicker()">Reset</div>
<!-- standard picker contents (transclusion is just an idea) -->
<ng-transclude></ng-transclude>
```

What are your thoughts about it?

**Comment by cmanunes** [comment]
Hi @indrimuska using ng-transclude is a good idea.
That way it would be easier to include buttons or operations as you wrote 👍

**Comment by indrimuska** [comment]
Ok, let's go for it!
At the moment, I'll keep open this PR as a reminder until a new solution is proposed (even by me). Thank you for your effort!

**Comment by indrimuska** [comment]
Hi @cmanunes, using [latest release](https://github.com/indrimuska/angular-moment-picker/releases/tag/0.7.1), you should be able to add custom template above and below the picker contents (inside the picker dialog) using the new `additions` properties like this:

```html
<span moment-picker="ctrl.date" format="YYYY-MM-DD" additions="{ top: 'moment-picker-top-addition.html' }">
	{{ ctrl.date || 'Click here to select a date' }}
</span>

<script type="text/ng-template" id="moment-picker-top-addition.html">
	<button class="btn btn-default btn-block" ng-click="reset()">Reset</button>
</script>
```

Note: `reset()` method is part of the picker scope.

**Pull request closed without merging**
